import { Montserrat } from '@next/font/google'
import type { ReactNode } from 'react'

import Footer from '@/components/Footer/Footer'
import Sidebar from '@/components/Sidebar/Sidebar'

import Header from '@/components/Header/Header'
import { SidebarContextProvider } from '@/context/SidebarContext'
import '@/styles/globals.scss'

const montserrat = Montserrat({ subsets: ['cyrillic', 'latin'] })

interface IRootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang='ru'>
      <head>
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className={montserrat.className}>
        <div className='wrapper'>
          <SidebarContextProvider>
            <Header />
            <div className='page-content'>
              <Sidebar />
              {children}
            </div>
            <Footer />
          </SidebarContextProvider>
        </div>
      </body>
    </html>
  )
}
