import Head from 'next/head'
import { ReactNode, useEffect, useState } from 'react'

import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import Sidebar from '@/components/Sidebar/Sidebar'
import { motion } from 'framer-motion'

interface IMainLayoutProps {
  children: ReactNode
  title?: string
}

export default function MainLayout({ children, title }: IMainLayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='wrapper'>
        <Header />
        <div className='page-content'>
          <Sidebar />
          <motion.div
            className='_container'
            initial={{ x: 300, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: 300, opacity: 0 }}
            transition={{
              type: 'spring',
              stiffness: 260,
              damping: 20,
            }}
          >
            {children}
          </motion.div>
        </div>
        <Footer />
      </div>
    </>
  )
}
